name: Test

on:
  push:
    branches: [main, staging]
  workflow_dispatch:

env:
  DEPLOY_FOLDER: ${{ %github.ref:ref=bla }}

jobs:
  combell-deploy:
    name: 'Combell deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy folder
        run: 
          echo ${{ env.DEPLOY_FOLDER }}
