name: Test

on:
  push:
    branches: [main, staging]
  workflow_dispatch:

env:
  DEPLOY_FOLDER: ${{ (github.ref == 'refs/heads/main' && 'production') || (github.ref == 'refs/heads/staging' && 'staging') }}

jobs:
  combell-deploy:
    name: 'Combell deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy folder
        run: 
          echo ${{ env.DEPLOY_FOLDER }} 
